basePath: /api/
definitions:
  csh_auth.UserInfo:
    properties:
      email:
        type: string
      groups:
        items:
          type: string
        type: array
      name:
        type: string
      preferred_username:
        type: string
      uuid:
        type: string
    type: object
  ldap.UserWUUID:
    properties:
      name:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
  models.Area:
    properties:
      description:
        type: string
      id:
        type: integer
      ldapGroup:
        type: string
      name:
        type: string
      photourl:
        type: string
    type: object
  models.CreateAreaRequest:
    properties:
      description:
        type: string
      ldapGroup:
        type: string
      name:
        type: string
      photourl:
        type: string
    type: object
  models.CreateTrainingRequest:
    properties:
      description:
        type: string
      questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
      requiredCorrect:
        type: integer
      title:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Question:
    properties:
      answer: {}
      id:
        type: integer
      label:
        type: string
      options:
        items:
          type: string
        type: array
      required:
        type: boolean
      type:
        type: string
    type: object
  models.Resource:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
  models.Submission:
    additionalProperties:
      type: string
    type: object
  models.Training:
    properties:
      description:
        type: string
      id:
        type: integer
      questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
      requiredCorrect:
        type: integer
      title:
        type: string
    type: object
  resources.RemoveResourceRequest:
    properties:
      id:
        type: integer
    type: object
  trainings.RemoveTrainingRequest:
    properties:
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: makedotcsh API
paths:
  /areas:
    get:
      description: Returns all areas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Area'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all areas
      tags:
      - areas
    post:
      consumes:
      - application/json
      description: Creates a new area
      parameters:
      - description: Area
        in: body
        name: area
        required: true
        schema:
          $ref: '#/definitions/models.CreateAreaRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create area
      tags:
      - areas
  /areas/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Deletes an area
      tags:
      - areas
    get:
      description: Returns an area by ID
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Area'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get area
      tags:
      - areas
    put:
      consumes:
      - application/json
      description: Updates an existing area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated area
        in: body
        name: area
        required: true
        schema:
          $ref: '#/definitions/models.CreateAreaRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update area
      tags:
      - areas
  /me:
    get:
      description: Returns information about the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/csh_auth.UserInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get authenticated user
      tags:
      - me
  /members/active:
    get:
      description: Returns all members in the LDAP active group
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ldap.UserWUUID'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get active CSH members
      tags:
      - members
  /resources:
    get:
      description: Returns all resources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Resource'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all resources
      tags:
      - resources
    post:
      consumes:
      - application/json
      description: Creates a new resource
      parameters:
      - description: Resource
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/models.Resource'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create resource
      tags:
      - resources
  /resources/{id}:
    delete:
      description: Deletes a resource by ID
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete resource
      tags:
      - resources
    get:
      description: Returns a resource by ID
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Resource'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get resource
      tags:
      - resources
    put:
      consumes:
      - application/json
      description: Updates an existing resource
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: integer
      - description: Resource
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/models.Resource'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update resource
      tags:
      - resources
  /resources/area/{id}:
    delete:
      consumes:
      - application/json
      description: Removes a resource from an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      - description: Resource removal request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/resources.RemoveResourceRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Remove resource from area
      tags:
      - resources
    get:
      description: Returns all resources associated with an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Resource'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get area resources
      tags:
      - resources
    post:
      consumes:
      - application/json
      description: Adds resources to an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      - description: Resource IDs
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Add resources to area
      tags:
      - resources
  /trainings:
    get:
      description: Returns all trainings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Training'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all trainings
      tags:
      - trainings
    post:
      consumes:
      - application/json
      description: Create a new training
      parameters:
      - description: Training
        in: body
        name: training
        required: true
        schema:
          $ref: '#/definitions/models.CreateTrainingRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create training
      tags:
      - trainings
  /trainings/{id}:
    delete:
      description: Deletes a training
      parameters:
      - description: Training ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete training
      tags:
      - trainings
    get:
      description: Returns a training by ID
      parameters:
      - description: Training ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Training'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get training
      tags:
      - trainings
    put:
      consumes:
      - application/json
      description: Updates an existing training
      parameters:
      - description: Training ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated training
        in: body
        name: training
        required: true
        schema:
          $ref: '#/definitions/models.CreateTrainingRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update training
      tags:
      - trainings
  /trainings/{id}/full:
    get:
      description: Returns a training by ID
      parameters:
      - description: Training ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Training'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get training
      tags:
      - trainings
  /trainings/{id}/submissions:
    post:
      consumes:
      - application/json
      description: Submits and grades a completed training
      parameters:
      - description: Training
        in: body
        name: training
        required: true
        schema:
          $ref: '#/definitions/models.Submission'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Submits and grades a completed training
      tags:
      - trainings
  /trainings/area/{id}:
    delete:
      consumes:
      - application/json
      description: Removes a training requirement from an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      - description: Training removal request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/trainings.RemoveTrainingRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Remove training from area
      tags:
      - trainings
    get:
      description: Returns all trainings required for an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Training'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get area trainings
      tags:
      - trainings
    post:
      consumes:
      - application/json
      description: Associates one or more trainings with an area
      parameters:
      - description: Area ID
        in: path
        name: id
        required: true
        type: integer
      - description: Training IDs
        in: body
        name: trainingIds
        required: true
        schema:
          items:
            type: integer
          type: array
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Add trainings to area
      tags:
      - trainings
swagger: "2.0"
